global:
  image:
    repository: ghcr.io/kl-engineering/${{ values.product_name }}-microgateway
    pullPolicy: Always
    tag: 0.0.3

  region: "uk"
  environment: "apifactory"

  imagePullSecrets:
    - name: dockerconfigjson-ghcr
  nameOverride: "${{ values.product_name }}-microgateway"
  fullnameOverride: "${{ values.product_name }}-microgateway"
